baseURL = "workshop.taskcat.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Taskcat Workshop"
theme = "learn"
uglyurls = true
#googleAnalytics = "UA-136137356-1"
sectionPagesMenu = "main"
pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "monokai"


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "blue"
showVisitedLinks = false
author = "Tony Vattathil"
description = "Taskcat Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true


# [menu]
#   [[menu.main]]
#     identifier = "Prerequisites"
#     name = "This is the Mu track"
#     title = "Workshop using Mu"
#     url = "/mu/"
#     weight = -110

#[[menu.shortcuts]]
#name = "<i class='fab fa-twitter fa-lg'></i> @twitter-handle"
#identifier = "tw"
#url = "https://twitter.com/intent/user?screen_name=name-to-display"
#weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
